<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-20T15:41:41 CEST" name="Suite" finished-at="2023-04-20T15:42:14 CEST" duration-ms="33365">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.LoginErrorValidation()[pri:0, instance:SeleniumFramework.tests.ErrorValidationsTest@3a0baae5]" name="LoginErrorValidation" class="SeleniumFramework.tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.SubmitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.tests.SubmitOrderTest@3d3e5463]" name="SubmitOrder" class="SeleniumFramework.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-04-20T15:41:41 CEST" name="Error Validations Test" finished-at="2023-04-20T15:42:12 CEST" duration-ms="31328">
      <class name="SeleniumFramework.tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.tests.ErrorValidationsTest@3a0baae5]" started-at="2023-04-20T15:41:41 CEST" name="launchApplication" finished-at="2023-04-20T15:41:51 CEST" duration-ms="9803" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:SeleniumFramework.tests.ErrorValidationsTest@3a0baae5]" started-at="2023-04-20T15:41:51 CEST" name="LoginErrorValidation" finished-at="2023-04-20T15:41:51 CEST" duration-ms="950" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at SeleniumFramework.tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.tests.ErrorValidationsTest@3a0baae5]" started-at="2023-04-20T15:41:52 CEST" name="tearDown" finished-at="2023-04-20T15:41:53 CEST" duration-ms="416" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.tests.ErrorValidationsTest@3a0baae5]" started-at="2023-04-20T15:41:53 CEST" name="launchApplication" finished-at="2023-04-20T15:41:57 CEST" duration-ms="4212" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValifation()[pri:0, instance:SeleniumFramework.tests.ErrorValidationsTest@3a0baae5]" started-at="2023-04-20T15:41:57 CEST" name="ProductErrorValifation" finished-at="2023-04-20T15:42:11 CEST" duration-ms="14480" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValifation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.tests.ErrorValidationsTest@3a0baae5]" started-at="2023-04-20T15:42:11 CEST" name="tearDown" finished-at="2023-04-20T15:42:12 CEST" duration-ms="493" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SeleniumFramework.tests.ErrorValidationsTest -->
    </test> <!-- Error Validations Test -->
    <test started-at="2023-04-20T15:41:41 CEST" name="Submit Order Test" finished-at="2023-04-20T15:42:14 CEST" duration-ms="33365">
      <class name="SeleniumFramework.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.tests.SubmitOrderTest@3d3e5463]" started-at="2023-04-20T15:41:41 CEST" name="launchApplication" finished-at="2023-04-20T15:41:51 CEST" duration-ms="9557" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.tests.SubmitOrderTest@3d3e5463]" started-at="2023-04-20T15:41:51 CEST" name="SubmitOrder" data-provider="getData" finished-at="2023-04-20T15:42:05 CEST" duration-ms="14589" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{psswd=Abc_12345, email=savelyeva1.20@gmail.com, productName=ADIDAS ORIGINAL}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at SeleniumFramework.tests.SubmitOrderTest.SubmitOrder(SubmitOrderTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.tests.SubmitOrderTest@3d3e5463]" started-at="2023-04-20T15:42:05 CEST" name="tearDown" finished-at="2023-04-20T15:42:06 CEST" duration-ms="146" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.tests.SubmitOrderTest@3d3e5463]" started-at="2023-04-20T15:42:06 CEST" name="launchApplication" finished-at="2023-04-20T15:42:10 CEST" duration-ms="3871" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="SubmitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.tests.SubmitOrderTest@3d3e5463]" started-at="2023-04-20T15:42:10 CEST" name="SubmitOrder" data-provider="getData" finished-at="2023-04-20T15:42:14 CEST" duration-ms="4354" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{psswd=Abc_12345, email=savelyeva1.20@gmail.com, productName=ZARA COAT 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SubmitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.tests.SubmitOrderTest@3d3e5463]" started-at="2023-04-20T15:42:14 CEST" name="tearDown" finished-at="2023-04-20T15:42:14 CEST" duration-ms="120" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:SeleniumFramework.tests.SubmitOrderTest@3d3e5463]" started-at="2023-04-20T15:42:14 CEST" name="OrderHistoryTest" finished-at="2023-04-20T15:42:14 CEST" depends-on-methods="SeleniumFramework.tests.SubmitOrderTest.SubmitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SeleniumFramework.tests.SubmitOrderTest.OrderHistoryTest() on instance SeleniumFramework.tests.SubmitOrderTest@3d3e5463 depends on not successfully finished methods 
[SeleniumFramework.tests.SubmitOrderTest.SubmitOrder() on instance SeleniumFramework.tests.SubmitOrderTest@3d3e5463]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SeleniumFramework.tests.SubmitOrderTest.OrderHistoryTest() on instance SeleniumFramework.tests.SubmitOrderTest@3d3e5463 depends on not successfully finished methods 
[SeleniumFramework.tests.SubmitOrderTest.SubmitOrder() on instance SeleniumFramework.tests.SubmitOrderTest@3d3e5463]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- SeleniumFramework.tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
